export const NFT_GENERATE_REQUEST = "NFT_GENERATE_REQUEST"
export const NFT_GENERATE_SUCCESS = "NFT_GENERATE_SUCCESS"
export const NFT_GENERATE_FAIL = "NFT_GENERATE_FAIL"

export const NFT_SAVE_REQUEST = "NFT_SAVE_REQUEST"
export const NFT_SAVE_SUCCESS = "NFT_SAVE_SUCCESS"
export const NFT_SAVE_FAIL = "NFT_SAVE_FAIL"

export const NFT_LIST_REQUEST = "NFT_LIST_REQUEST"
export const NFT_LIST_SUCCESS = "NFT_LIST_SUCCESS"
export const NFT_LIST_FAIL = "NFT_LIST_FAIL"
